In [1]:
import pandas as pd 
import numpy as np
import random
import matplotlib.pyplot as plt
from vnstock import Listing

In [2]:
pool_lst_v2 = [
"FPT","CMG","ELC",#tech
"VGI","DCL",#others
"SSI","VPB","TCB","VCB","VND","TPB","BID","CTG",#fin
"VRE","VIC","VHM","CEO","DXG",#fin
"MWG","VJC","TNG","VGT","TCM","PNJ","MSH",#goods
"HAG","HNG","MSN","DBC","VNM","VHC","ANV",#goods
"GEX","VCG","CII","VSC","HUT","HBC",#industrials
"HPG","GVR","NKG","DPM","HSG",#industrials
"PVD","PVS","BSR",#industrials
"POW"#industrials
]
len(pool_lst_v2)
#remove BAF and KHG because of missing value
#remove HVN due to low ROE

47

-------------------------------------------------------- pv

In [26]:
open_data_lst = []
not_found_lst=[]
for i0 in pool_lst_v2:
    try:
        temp_df = pd.read_csv(f"raw_data/pv/{i0}.csv")
        temp_df = temp_df[['time','close']]
        temp_df.columns = ['time',i0]
        temp_df.set_index("time")
        open_data_lst.append(temp_df)
    except:
        not_found_lst.append(i0)
tmp_df = pd.read_csv("raw_data/pv/FPT.csv")
tmp_df_date = tmp_df['time']
timerange = np.array(tmp_df_date)
open_data_df = pd.DataFrame(data=timerange)
open_data_df.columns = ['time']
for i1 in open_data_lst:
    open_data_df = open_data_df.merge(i1, how="outer")
open_data_df = open_data_df.ffill(axis=0)

In [24]:
#open_data_df['POW']=open_data_df['POW'].fillna(14)
open_data_df

,time,FPT,CMG,ELC,VGI,DCL,SSI,VPB,TCB,VCB,...,HBC,HPG,GVR,NKG,DPM,HSG,PVD,PVS,BSR,POW
0,2020-01-05,21.03,16.33,3.10,24.75,27.90,6.58,6.66,11.17,38.82,...,9.75,8.33,10.41,3.88,4.35,5.29,11.26,15.22,4.63,11.16
1,2020-01-12,20.99,15.97,3.36,22.87,24.60,6.60,6.87,10.94,38.65,...,10.01,8.34,9.96,4.58,4.33,5.36,11.22,15.48,4.40,10.59
2,2020-01-19,21.03,15.74,3.28,23.86,24.90,6.94,7.15,11.05,40.80,...,9.80,8.62,10.14,5.07,4.25,5.60,10.85,15.06,4.18,10.30
3,2020-01-26,20.63,15.69,3.29,26.34,25.00,6.96,7.70,11.43,40.33,...,10.05,9.07,10.76,4.86,4.28,5.95,11.08,15.39,4.80,10.59
4,2020-02-02,18.98,14.60,3.31,24.75,26.00,6.38,7.33,10.20,38.30,...,8.94,8.31,9.61,4.27,3.94,5.40,9.85,13.71,4.35,10.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2025-10-12,96.10,40.00,21.43,68.70,29.50,40.70,32.10,39.35,64.20,...,7.20,29.60,28.05,17.90,24.45,19.00,21.60,32.80,18.08,14.60
302,2025-10-19,88.10,37.30,20.75,65.30,29.50,40.80,31.95,40.65,61.90,...,6.50,28.00,27.10,17.75,23.15,18.25,20.00,30.40,17.15,14.15
303,2025-10-26,97.70,38.75,21.20,70.90,31.00,36.00,29.20,36.10,59.50,...,6.30,26.40,26.55,15.50,23.00,16.30,20.15,31.20,16.90,13.40
304,2025-11-02,103.90,41.90,21.95,79.40,32.95,34.30,28.70,35.10,59.60,...,6.70,26.70,29.05,16.00,24.00,16.75,21.65,32.80,16.65,14.35
305,2025-11-09,100.90,39.30,21.20,77.20,34.50,34.90,29.25,34.10,60.80,...,6.40,26.30,29.05,16.95,24.90,17.10,24.25,34.10,16.80,14.70

In [27]:
open_data_df.to_csv("execution_data/close.csv")

---------------------------------------------------------- fundamental

In [17]:
tmp_df = pd.read_csv("raw_data/pv/FPT.csv")
tmp_df_date = tmp_df['time']
tmp_df_date=tmp_df_date.reset_index()
tmp_df_date=tmp_df_date.drop(['index'],axis=1)
tmp_df_date['time'] = tmp_df_date['time']
tmp_df_date['time_format'] = pd.to_datetime(tmp_df_date['time'], format='%Y-%m-%d')
tmp_df_date['year'] = tmp_df_date['time_format'].dt.year
tmp_df_date['quarter'] = tmp_df_date['time_format'].dt.quarter
tmp_df_date = tmp_df_date.drop(['time_format'],axis=1)
timerange = np.array(tmp_df_date)

In [18]:
tmp_df_date

           time  year  quarter
0    2020-01-05  2020        1
1    2020-01-12  2020        1
2    2020-01-19  2020        1
3    2020-01-26  2020        1
4    2020-02-02  2020        1
..          ...   ...      ...
301  2025-10-12  2025        4
302  2025-10-19  2025        4
303  2025-10-26  2025        4
304  2025-11-02  2025        4
305  2025-11-09  2025        4

[306 rows x 3 columns]

In [ ]:
# pv_all['time'] = pd.to_datetime(pv_all['time'], format='%Y-%m-%d')
# pv_all['year'] = pv_all['time'].dt.year
# pv_all['quarter'] = pv_all['time'].dt.quarter

In [19]:
fundamental_data_lst = []
not_found_lst=[]
for i0 in pool_lst_v2:
    try:
        temp_df = pd.read_csv(f"raw_data/financeratio/{i0}.csv")
        temp_df = temp_df[['year','quarter','roe']]
        temp_df.columns = ['year','quarter',i0]


        temp_df_processed = pd.merge(tmp_df_date, temp_df, on=['year','quarter'], how='inner')
        temp_df_processed = temp_df_processed.drop(['year','quarter'],axis=1)
        fundamental_data_lst.append(temp_df_processed)
    except:
        not_found_lst.append(i0)

#tmp_df = pd.read_csv("raw_data/financeratio/VCB.csv")
tmp_df_date2 = tmp_df['time']
timerange2 = np.array(tmp_df_date2)
fundamental_data_df = pd.DataFrame(data=timerange2)
fundamental_data_df.columns = ['time']
for i1 in fundamental_data_lst:
    fundamental_data_df = fundamental_data_df.merge(i1, how="outer")
fundamental_data_df=fundamental_data_df.replace(0, np.nan).ffill()
#fundamental_data_df = fundamental_data_df.fillna(0)

In [20]:
fundamental_data_df

,time,FPT,CMG,ELC,VGI,DCL,SSI,VPB,TCB,VCB,...,HBC,HPG,GVR,NKG,DPM,HSG,PVD,PVS,BSR,POW
0,2020-01-05,0.195676,0.071317,0.039956,0.079643,0.114733,0.072910,0.221472,0.172719,0.218914,...,0.086647,0.169906,0.066403,0.063016,0.053351,0.113738,0.021467,0.036743,-0.002984,0.070153
1,2020-01-12,0.195676,0.071317,0.039956,0.079643,0.114733,0.072910,0.221472,0.172719,0.218914,...,0.086647,0.169906,0.066403,0.063016,0.053351,0.113738,0.021467,0.036743,-0.002984,0.070153
2,2020-01-19,0.195676,0.071317,0.039956,0.079643,0.114733,0.072910,0.221472,0.172719,0.218914,...,0.086647,0.169906,0.066403,0.063016,0.053351,0.113738,0.021467,0.036743,-0.002984,0.070153
3,2020-01-26,0.195676,0.071317,0.039956,0.079643,0.114733,0.072910,0.221472,0.172719,0.218914,...,0.086647,0.169906,0.066403,0.063016,0.053351,0.113738,0.021467,0.036743,-0.002984,0.070153
4,2020-02-02,0.195676,0.071317,0.039956,0.079643,0.114733,0.072910,0.221472,0.172719,0.218914,...,0.086647,0.169906,0.066403,0.063016,0.053351,0.113738,0.021467,0.036743,-0.002984,0.070153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2025-10-12,0.273707,0.130680,0.115982,0.255022,0.023207,0.130601,0.135363,0.136738,0.167670,...,0.109701,0.120224,0.113152,0.031463,0.073454,0.065082,0.054572,0.104111,0.036705,0.058115
302,2025-10-19,0.273707,0.130680,0.115982,0.255022,0.023207,0.130601,0.135363,0.136738,0.167670,...,0.109701,0.120224,0.113152,0.031463,0.073454,0.065082,0.054572,0.104111,0.036705,0.058115
303,2025-10-26,0.273707,0.130680,0.115982,0.255022,0.023207,0.130601,0.135363,0.136738,0.167670,...,0.109701,0.120224,0.113152,0.031463,0.073454,0.065082,0.054572,0.104111,0.036705,0.058115
304,2025-11-02,0.273707,0.130680,0.115982,0.255022,0.023207,0.130601,0.135363,0.136738,0.167670,...,0.109701,0.120224,0.113152,0.031463,0.073454,0.065082,0.054572,0.104111,0.036705,0.058115
305,2025-11-09,0.273707,0.130680,0.115982,0.255022,0.023207,0.130601,0.135363,0.136738,0.167670,...,0.109701,0.120224,0.113152,0.031463,0.073454,0.065082,0.054572,0.104111,0.036705,0.058115

In [22]:
fundamental_data_df.to_csv("execution_data/roe.csv")

______________________________________ special

In [6]:
#open_data_df
def correlation(X,Y):
    if len(X)==len(Y):
        Sum_xy = sum((X-np.mean(X))*(Y-np.mean(Y)))
        Sum_x_squared = sum((X-np.mean(X))**2)
        Sum_y_squared = sum((Y-np.mean(Y))**2)       
        corr = Sum_xy / np.sqrt(Sum_x_squared * Sum_y_squared)
    return float(corr)

from vnstock import Quote
vnind = Quote(symbol='VNINDEX', source='VCI')
vnindex_df = vnind.history(start='2019-01-01', interval='1W')
vnindex_df = vnindex_df[['time','close']]
vnindex_df['time'] = vnindex_df['time'].apply(lambda x: x.strftime('%Y-%m-%d'))
vnindex_df=vnindex_df.ffill(axis=0)


timerange = vnindex_df['time']
#corr_df.columns = ['time']
#fpt_close = fpt_close.ffill(axis=0)

backtime = 52
tmp_lst = []
for i2 in pool_lst_v2:
    tmp_lst_backtime_vnd = []
    for i0 in range(len(timerange)):
        tmp_add =[]
        for j0 in range(backtime):
            tmp_add.append(float(vnindex_df['close'].values[i0-j0]))
        tmp_lst_backtime_vnd.append(tmp_add)
    tmp_lst_backtime_vnd=tmp_lst_backtime_vnd[backtime:]
    
    stock_df = open_data_df[['time',i2]]
    tmp_lst_backtime_stock = []
    for i0 in range(len(timerange)):
        tmp_add =[]
        for j0 in range(backtime):
            tmp_add.append(float(stock_df[i2].values[i0-j0]))
        tmp_lst_backtime_stock.append(tmp_add)
    tmp_lst_backtime_stock=tmp_lst_backtime_stock[backtime:]

    corr_lst = []
    for i1 in range(len(timerange)-backtime):
        corr_lst.append(correlation(tmp_lst_backtime_vnd[i1],tmp_lst_backtime_stock[i1]))
    tmp_lst.append(corr_lst)

In [13]:
corr_df = pd.DataFrame(data=tmp_lst)
corr_df=corr_df.T

columns_names = list(open_data_df.columns.values[1:])
corr_df.columns = columns_names
timerange_corr = list(timerange[backtime:])
corr_df['time'] = timerange_corr
corr_df = corr_df[['time'] + [col for col in corr_df.columns if col != 'time']]
corr_df

,time,FPT,CMG,ELC,VGI,DCL,SSI,VPB,TCB,VCB,...,HBC,HPG,GVR,NKG,DPM,HSG,PVD,PVS,BSR,POW
0,2020-01-05,0.549963,0.599402,-0.558302,0.718231,0.359133,-0.154662,0.470984,-0.239023,0.614134,...,-0.058019,0.096819,0.585254,-0.036502,-0.536667,0.416673,0.570887,0.261397,-0.322138,-0.322434
1,2020-01-12,0.509301,0.552135,-0.523853,0.682871,0.275819,-0.113744,0.456535,-0.196646,0.562680,...,-0.034069,0.073691,0.551372,-0.007248,-0.495737,0.351813,0.512778,0.206862,-0.273318,-0.308550
2,2020-01-19,0.469924,0.502433,-0.489282,0.638967,0.181678,-0.100475,0.450310,-0.123774,0.505589,...,-0.030979,0.047628,0.513030,0.009434,-0.427317,0.264712,0.418721,0.125628,-0.239288,-0.290981
3,2020-01-26,0.434683,0.445657,-0.440985,0.580643,0.080286,-0.074697,0.486539,-0.034800,0.461797,...,-0.036944,0.054333,0.452178,0.041219,-0.376300,0.187160,0.319175,0.039376,-0.245625,-0.284516
4,2020-02-02,0.351060,0.378536,-0.377223,0.514813,-0.132629,0.050864,0.430648,0.133657,0.326027,...,0.043322,-0.068605,0.429342,-0.078047,-0.204904,0.003982,0.334423,0.041946,-0.137530,-0.108808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,2025-10-05,-0.452318,-0.148944,-0.026416,-0.242953,-0.215984,0.949426,0.941079,0.940152,0.468008,...,0.778495,0.957122,-0.017531,0.635205,0.951144,0.492880,-0.028065,0.292182,0.706239,0.950504
301,2025-10-12,-0.475475,-0.148402,-0.054096,-0.284048,-0.101641,0.955919,0.945452,0.943556,0.487655,...,0.767369,0.961859,-0.031176,0.679837,0.938920,0.531018,-0.006472,0.306211,0.755977,0.937821
302,2025-10-19,-0.512623,-0.165839,-0.101689,-0.337953,-0.012462,0.961026,0.949408,0.948715,0.480308,...,0.736531,0.961436,-0.051486,0.711712,0.921066,0.551950,-0.015723,0.286824,0.784450,0.922690
303,2025-10-26,-0.524872,-0.168916,-0.147675,-0.375172,0.079439,0.962517,0.951012,0.947469,0.449657,...,0.703917,0.956668,-0.077986,0.715879,0.910498,0.539888,-0.010775,0.289382,0.803828,0.901846
304,2025-11-02,-0.524239,-0.154521,-0.162913,-0.378540,0.161895,0.962708,0.953291,0.946697,0.435853,...,0.691692,0.956374,-0.067540,0.736631,0.909579,0.549740,0.021279,0.316852,0.816390,0.900544

In [14]:
corr_df.to_csv("execution_data/corr_vnindex_52w_plus1.csv")

In [37]:
corr_df

,FPT,CMG,ELC,VGI,DCL,SSI,VPB,TCB,VCB,VND,...,HPG,GVR,NKG,DPM,HSG,PVD,PVS,BSR,POW,time
0,1.549963,1.599119,0.454188,1.718231,1.355619,0.846047,1.473977,0.762200,1.614592,0.770770,...,1.099235,1.583468,0.969187,0.460834,1.418305,1.569553,1.261152,0.677055,0.676970,2020-01-05
1,1.509076,1.550501,0.502701,1.684002,1.259975,0.887583,1.467128,0.804748,1.562779,0.800059,...,1.078501,1.548491,1.014959,0.499264,1.356173,1.510638,1.207141,0.722759,0.684197,2020-01-12
2,1.469692,1.500764,0.538740,1.641331,1.166147,0.900820,1.468811,0.878413,1.511365,0.784259,...,1.052219,1.513531,1.030746,0.566791,1.270535,1.425176,1.129279,0.755079,0.697415,2020-01-19
3,1.435152,1.446840,0.581388,1.576583,1.075621,0.922376,1.510602,0.963816,1.467423,0.795973,...,1.043140,1.451420,1.049539,0.617885,1.179825,1.330270,1.044375,0.746917,0.704971,2020-01-26
4,1.317439,1.348733,0.682492,1.509736,0.863945,1.037391,1.533850,1.089958,1.322459,0.836732,...,0.912941,1.412436,0.922637,0.769168,0.996115,1.298828,1.010000,0.846390,0.854427,2020-02-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,1.684752,1.112920,1.893499,1.747971,1.898540,1.945928,1.886987,1.927350,1.769853,1.903702,...,1.740728,1.872059,1.803744,1.698551,1.849853,1.755224,1.695629,1.954753,1.841102,2025-10-05
301,1.694892,1.245044,1.899195,1.754718,1.909328,1.952093,1.895682,1.933404,1.772179,1.914907,...,1.756796,1.889684,1.810856,1.727570,1.863431,1.762947,1.703707,1.958953,1.846815,2025-10-12
302,1.704253,1.334653,1.904498,1.761523,1.916414,1.956340,1.902979,1.939006,1.775635,1.922354,...,1.770738,1.902918,1.818379,1.749540,1.876593,1.770560,1.711605,1.962380,1.852600,2025-10-19
303,1.714768,1.380626,1.910362,1.767567,1.918573,1.957628,1.908590,1.943288,1.782114,1.925065,...,1.780451,1.909576,1.825355,1.770139,1.888765,1.778581,1.721237,1.964850,1.859263,2025-10-26
304,1.729170,1.404439,1.905795,1.771939,1.917769,1.947322,1.912105,1.939855,1.789599,1.920255,...,1.788910,1.910773,1.831646,1.786307,1.900598,1.784188,1.735125,1.962811,1.859808,2025-11-02